### ISSUE TITLE
questions about LDR and HDR pre-processing

### ISSUE THREAD

**Issue by peiyaoooo** [LWT3437/LANet#4]
Hi, thank you for this amazing work! 
And I have some questions about the LDR and HDR pre-processing to ensure scale-invariant.

In https://github.com/LWT3437/LANet/blob/d45c86406208f81105e3960889b28ed9b50f8ad6/LANet/src/utils.py#L46,
The linear LDR image is squared and then subtracted by  1. I could't get the aim of this operation.

Besides, in the loading procedure (https://github.com/LWT3437/LANet/blob/d45c86406208f81105e3960889b28ed9b50f8ad6/LANet/src/utils.py#L21),
 the LDR and HDR images are all loaded via cv2. But the LDR and HDR image are in different format right?  like LDR in 8 bit and HDR in 14/16 bit.

Hope for your reply and thank you again.

**Comment by LWT3437** [comment]
@peiyaoooo for the first question, this operation aims to normalize LDR valuea to the range [-1, 1], which is the common method for training.

And we use [OpenEXR](https://www.openexr.com/) format to represent the HDR image, which is compatible with opencv imread function (the arg '-1' can handle this).

**Comment by peiyaoooo** [comment]
Oh thank you very much!
And I just found that I made a silly error.
It is "LDR = LDR **2 -1" in my head and I couldn't understand this comand.  It's my fault. So sorry about this.
And thank you for you reply again.
